name: Build the game
on:
  push:
    branches: [master]

jobs:
  BuildDesktop:
    name: ${{ matrix.name }}
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            exportPath: windows
            artifactName: H-Slice_0.2.1_Windows
            cacheLibrariesPath: H-Slice_0.2.1.desktop-cache
            cachePath: H-Slice_0.2.1.build-windows
            artifactPath: export\release\windows\bin\*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: linux
            exportPath: linux
            artifactName: H-Slice_0.2.1_Linux
            cachePath: H-Slice_0.2.1.build-linux
            cacheLibrariesPath: H-Slice_0.2.1.desktop-cache
            artifactPath: export/release/linux/bin/*
          - name: macOS x86_64
            os: macos-14
            buildArgs: "mac -64 -D HXCPP_M64"
            cachePath: H-Slice_0.2.1.build-macos_m64
            exportPath: macos
            cacheLibrariesPath: H-Slice_0.2.1.mobile-cache
            artifactName: H-Slice_0.2.1_macOS_x64
            artifactPath: export/release/macos/bin/*
            
          - name: macOS AArch64
            os: macos-15
            buildArgs: mac
            exportPath: macos
            cachePath: H-Slice_0.2.1.build-macos
            cacheLibrariesPath: H-Slice_0.2.1.mobile-cache
            artifactName: H-Slice_0.2.1_macOS_arm64
            artifactPath: export/release/macos/bin/*
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{matrix.cachePath}}
  BuildMobile:
    permissions: write-all
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: macos-15
            exportPath: android
            buildArgs: "android"
            cacheLibrariesPath: H-Slice_0.2.1.mobile-cache
            artifactName: H-Slice_0.2.1_Android
            cachePath: H-Slice_0.2.1.build-android
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: Android-profiled
            os: macos-15
            exportPath: android
            buildArgs: "android -DPROFILE_BUILD"
            cacheLibrariesPath: H-Slice_0.2.1.mobile-cache
            artifactName: H-Slice_0.2.1.android-audited
            cachePath: H-Slice_0.2.1.build-android-profile
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -nosign"
            exportPath: ios
            cacheLibrariesPath: H-Slice_0.2.1.mobile-cache
            artifactName: H-Slice_0.2.1_iOS
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
            cachePath: H-Slice_0.2.1.build-ios
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{matrix.cachePath}}
