name: Build deps
on:
  workflow_dispatch:

jobs:
  BuildCaches:
    name: ${{ matrix.name }}
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            setupScript: sh ./setup/unix.sh
            CACHE_NAME: H-Slice_0.2.1_desktop-cache

          - name: Mobile
            os: macos-latest
            setupScript: sh ./setup/mobile.sh
            CACHE_NAME: H-Slice_0.2.1_mobile-cache
    uses: ./.github/workflows/dependencies.yml
    with:
      os: ${{ matrix.os }}
      CACHE_NAME: ${{ matrix.CACHE_NAME }}
      setupScript: ${{ matrix.setupScript }}